// <auto-generated />
using System;
using Konyvtar.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konyvtar.Migrations
{
    [DbContext(typeof(KonyvtarContext))]
    [Migration("20260122123151_szul_hely_fix")]
    partial class szul_hely_fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Konyvtar.Models.Diakok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Osztaly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Szul_hely")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Szul_ido")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Diakok");
                });

            modelBuilder.Entity("Konyvtar.Models.Kolcsonzesek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Diak_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Kolcsonzes_datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Konyv_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Visszahozatal_datum")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Visszahozatal_hatarido")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Diak_id");

                    b.HasIndex("Konyv_id");

                    b.ToTable("Kolcsonzesek");
                });

            modelBuilder.Entity("Konyvtar.Models.Konyvek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ajanlo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cim_hun")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kiadas_eve")
                        .HasColumnType("int");

                    b.Property<string>("Kiado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Max_kolcsonzes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Peldanyszam")
                        .HasColumnType("int");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Szpeldany")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Konyvek");
                });

            modelBuilder.Entity("Konyvtar.Models.Mufajkonyvek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Konyv_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mufaj_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Konyv_id");

                    b.HasIndex("Mufaj_id");

                    b.ToTable("Mufajkonyvek");
                });

            modelBuilder.Entity("Konyvtar.Models.Mufajok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mufajok");
                });

            modelBuilder.Entity("Konyvtar.Models.Olvasojegyek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Diak_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Kiadas_datum")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Lejarati_datum")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Diak_id")
                        .IsUnique();

                    b.ToTable("Olvasojegyek");
                });

            modelBuilder.Entity("Konyvtar.Models.Szerzok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ismerteto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Szul_hely")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Szul_ido")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Szerzok");
                });

            modelBuilder.Entity("Konyvtar.Models.Szerzokonyvek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Konyv_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Szerzo_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Konyv_id");

                    b.HasIndex("Szerzo_id");

                    b.ToTable("Szerzokonyvek");
                });

            modelBuilder.Entity("Konyvtar.Models.Kolcsonzesek", b =>
                {
                    b.HasOne("Konyvtar.Models.Diakok", "Diakok")
                        .WithMany("Kolcsonzesek")
                        .HasForeignKey("Diak_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyvtar.Models.Konyvek", "Konyvek")
                        .WithMany("Kolcsonzesek")
                        .HasForeignKey("Konyv_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diakok");

                    b.Navigation("Konyvek");
                });

            modelBuilder.Entity("Konyvtar.Models.Mufajkonyvek", b =>
                {
                    b.HasOne("Konyvtar.Models.Konyvek", "Konyvek")
                        .WithMany("Mufajkonyvek")
                        .HasForeignKey("Konyv_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyvtar.Models.Mufajok", "Mufajok")
                        .WithMany("Mufajkonyvek")
                        .HasForeignKey("Mufaj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konyvek");

                    b.Navigation("Mufajok");
                });

            modelBuilder.Entity("Konyvtar.Models.Olvasojegyek", b =>
                {
                    b.HasOne("Konyvtar.Models.Diakok", "Diakok")
                        .WithOne("Olvasojegyek")
                        .HasForeignKey("Konyvtar.Models.Olvasojegyek", "Diak_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diakok");
                });

            modelBuilder.Entity("Konyvtar.Models.Szerzokonyvek", b =>
                {
                    b.HasOne("Konyvtar.Models.Konyvek", "Konyvek")
                        .WithMany("Szerzokonyvek")
                        .HasForeignKey("Konyv_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyvtar.Models.Szerzok", "Szerzok")
                        .WithMany("Szerzokonyvek")
                        .HasForeignKey("Szerzo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konyvek");

                    b.Navigation("Szerzok");
                });

            modelBuilder.Entity("Konyvtar.Models.Diakok", b =>
                {
                    b.Navigation("Kolcsonzesek");

                    b.Navigation("Olvasojegyek");
                });

            modelBuilder.Entity("Konyvtar.Models.Konyvek", b =>
                {
                    b.Navigation("Kolcsonzesek");

                    b.Navigation("Mufajkonyvek");

                    b.Navigation("Szerzokonyvek");
                });

            modelBuilder.Entity("Konyvtar.Models.Mufajok", b =>
                {
                    b.Navigation("Mufajkonyvek");
                });

            modelBuilder.Entity("Konyvtar.Models.Szerzok", b =>
                {
                    b.Navigation("Szerzokonyvek");
                });
#pragma warning restore 612, 618
        }
    }
}
